### ISSUE TITLE
Crashes when opening an app from recents while using Android P-ify

### ISSUE THREAD

**Issue by jahirfiquitiva** [paphonb/PixelLauncherModV6#3]
![screenshot_matlog_20180511-122814](https://user-images.githubusercontent.com/10360816/39938261-fc964486-5517-11e8-8809-a2c1b94f10b7.png)

**Comment by jahirfiquitiva** [comment]
Looks like it only happens when this launcher is not the default launcher. I'm using Nova as default (and would like to keep doing so).

Thanks in advance

**Comment by paphonb** [comment]
This is now fixed in P-ify.

**Comment by jahirfiquitiva** [comment]
Thank you so much @paphonb
