### ISSUE TITLE
Swipe down for notifications and quick settings is not working , rooted using P-ify

### ISSUE THREAD

**Issue by abhishek2108** [paphonb/PixelLauncherModV6#5]
Not able to swipe down from anywhere on the screen to get notifications and quick settings panel, was able to do before P-ify and when not  rooted.

**Comment by abhishek2108** [comment]
It works when 'swipe up from dock to switch apps ' options is disabled in P-ify , but not when it's enabled ..

**Comment by paphonb** [comment]
Sorry, but all features in P recents section is not supported. It can cause problems.
