### ISSUE TITLE
Google feed not working

### ISSUE THREAD

**Issue by pathania08** [paphonb/PixelLauncherModV6#8]
Swiping from left doesn't work sometimes. Can't access to google feed . please fix

**Comment by user22555** [comment]
Same as #6 probably, using back instead of home button keeps the feed working.

**Comment by pathania08** [comment]
I don't get it, please explain how to make it work? It's not working right now, neither is the Google search bar at the bottom on the home page.

**Comment by paphonb** [comment]
Recent google app version tends to bug things out. This also happen on other launchers as well.

**Comment by pathania08** [comment]
I updated the Google app but still the same issue. Google feed doesn't work please do something about it.

**Comment by paphonb** [comment]
I'm sorry but I can't do anything about it.
